<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AetherBar.Core\AetherBar.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PInvoke.Kernel32" Version="0.7.124" />
    <PackageReference Include="PInvoke.User32" Version="0.7.124" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
